import { StyleSheet } from '@react-pdf/renderer';

export const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontSize: 9,
    fontFamily: 'Helvetica',
    color: '#222',
  },
  header: {
    marginBottom: 16,
    borderBottom: 2,
    borderBottomColor: '#0f172a',
    paddingBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  logo: {
    width: 60,
    height: 60,
    objectFit: 'contain',
  },
  companyName: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
  },
  companyInfo: {
    fontSize: 8,
    color: '#555',
    marginTop: 2,
  },
  headerRight: {
    alignItems: 'flex-end',
  },
  title: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 4,
  },
  orderNumber: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: '#0f172a',
  },
  orderDate: {
    fontSize: 9,
    color: '#555',
    marginTop: 2,
  },
  sectionTitle: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    marginTop: 14,
    marginBottom: 6,
    paddingBottom: 3,
    borderBottom: 1,
    borderBottomColor: '#0f172a',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  infoRow: {
    flexDirection: 'row',
    marginBottom: 3,
  },
  infoLabel: {
    width: 110,
    fontFamily: 'Helvetica-Bold',
    fontSize: 9,
  },
  infoValue: { flex: 1, fontSize: 9 },
  table: { marginTop: 6, marginBottom: 6 },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f1f5f9',
    borderBottomWidth: 1,
    borderBottomColor: '#0f172a',
    paddingVertical: 5,
    paddingHorizontal: 4,
    fontFamily: 'Helvetica-Bold',
    fontSize: 8,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: '#cbd5e1',
    paddingVertical: 5,
    paddingHorizontal: 4,
    fontSize: 8,
  },
  // Invoices columns
  invDate: { width: '14%' },
  invDue: { width: '14%' },
  invVoucher: { width: '24%' },
  invCurrency: { width: '12%', textAlign: 'center' },
  invTotal: { width: '18%', textAlign: 'right' },
  invApplied: { width: '18%', textAlign: 'right' },
  // Payments columns
  payMethod: { width: '20%' },
  payDetail: { width: '40%' },
  payRef: { width: '20%' },
  payAmount: { width: '20%', textAlign: 'right' },
  totalsBox: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  totalsLabel: {
    width: 140,
    textAlign: 'right',
    paddingRight: 10,
    fontFamily: 'Helvetica-Bold',
  },
  totalsValue: {
    width: 110,
    textAlign: 'right',
    fontFamily: 'Helvetica-Bold',
  },
  grandTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginTop: 8,
    backgroundColor: '#0f172a',
    color: '#ffffff',
    fontFamily: 'Helvetica-Bold',
    fontSize: 12,
  },
  amountWords: {
    marginTop: 8,
    padding: 8,
    backgroundColor: '#f8fafc',
    borderLeft: 3,
    borderLeftColor: '#0f172a',
    fontSize: 9,
    fontFamily: 'Helvetica-Oblique',
  },
  signatureSection: {
    marginTop: 40,
    borderTop: 1,
    borderTopColor: '#0f172a',
    paddingTop: 30,
  },
  signatureRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  signatureBox: {
    width: '45%',
    borderTop: 0.5,
    borderTopColor: '#222',
    paddingTop: 4,
    fontSize: 8,
    textAlign: 'center',
  },
  signatureNote: {
    fontSize: 8,
    color: '#555',
    marginBottom: 24,
  },
  footer: {
    marginTop: 30,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#cbd5e1',
    fontSize: 7,
    color: '#666',
    textAlign: 'center',
  },
});
