import { AlertComponent } from '@/components/AlertComponent'
import Link from 'next/link'
import { columns } from './columns'
import { DataTable } from './data-table'

const EmployeePage = () => {

  //Crear un arreglo de empleados
  const data = [
    {
      full_name: 'Juan Perez',
      email: 'empleado1@hotmail.com',
      cuil: '20-12345678-9',
      document_number: '12345678',
      hierarchical_position: 'Empleado',
      company_position: 'Empleado',
      normal_hours: '8',
      type_of_contract: 'A tiempo indeterminado',
      allocated_to: 'Empresa 1', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'Perez',
      firstname: 'Juan',
      document_type: 'DNI',
      birthplace: 'Buenos Aires',
      gender: 'Masculino',
      marital_status: 'Soltero',
      level_of_education: 'Universitario',
      street: 'Calle 123',
      street_number: '123',
      province: 'Buenos Aires',
      postal_code: '1234',
      phone: '12345678',
      file: '123',
      date_of_admission: '01/01/2021',
      affiliate_status: 'Fuera de convenio',
      city: 'Buenos Aires',
      hierrical_position: 'Empleado',
      workflow_diagram: '123',
    },
    {
      full_name: 'Maria Rodriguez',
      email: 'maria.rodriguez@example.com',
      cuil: '27-98765432-1',
      document_number: '98765432',
      hierarchical_position: 'Gerente',
      company_position: 'Gerente',
      normal_hours: '8',
      type_of_contract: 'A tiempo determinado',
      allocated_to: 'Empresa 2', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'Rodriguez',
      firstname: 'Maria',
      document_type: 'DNI',
      birthplace: 'Córdoba',
      gender: 'Femenino',
      marital_status: 'Casada',
      level_of_education: 'Posgrado',
      street: 'Avenida 123',
      street_number: '456',
      province: 'Córdoba',
      postal_code: '5678',
      phone: '98765432',
      file: '456',
      date_of_admission: '01/02/2022',
      affiliate_status: 'Convenio',
      city: 'Córdoba',
      hierrical_position: 'Gerente',
      workflow_diagram: '456',
    },
    {
      full_name: 'Ana López',
      email: 'ana.lopez@example.com',
      cuil: '23-45678901-2',
      document_number: '45678901',
      hierarchical_position: 'Supervisor',
      company_position: 'Supervisor',
      normal_hours: '8',
      type_of_contract: 'A tiempo indeterminado',
      allocated_to: 'Empresa 3', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'López',
      firstname: 'Ana',
      document_type: 'DNI',
      birthplace: 'Mendoza',
      gender: 'Femenino',
      marital_status: 'Soltera',
      level_of_education: 'Universitario',
      street: 'Calle 456',
      street_number: '789',
      province: 'Mendoza',
      postal_code: '9012',
      phone: '45678901',
      file: '789',
      date_of_admission: '01/03/2023',
      affiliate_status: 'Fuera de convenio',
      city: 'Mendoza',
      hierrical_position: 'Supervisor',
      workflow_diagram: '789',
    },

    {
      full_name: 'Pedro Gómez',
      email: 'pedro.gomez@example.com',
      cuil: '24-56789012-3',
      document_number: '56789012',
      hierarchical_position: 'Analista',
      company_position: 'Analista',
      normal_hours: '8',
      type_of_contract: 'A tiempo determinado',
      allocated_to: 'Empresa 4', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'Gómez',
      firstname: 'Pedro',
      document_type: 'DNI',
      birthplace: 'Rosario',
      gender: 'Masculino',
      marital_status: 'Soltero',
      level_of_education: 'Terciario',
      street: 'Avenida 789',
      street_number: '012',
      province: 'Santa Fe',
      postal_code: '3456',
      phone: '56789012',
      file: '012',
      date_of_admission: '01/04/2024',
      affiliate_status: 'Convenio',
      city: 'Rosario',
      hierrical_position: 'Analista',
      workflow_diagram: '012',
    },

    {
      full_name: 'Laura Fernández',
      email: 'laura.fernandez@example.com',
      cuil: '25-67890123-4',
      document_number: '67890123',
      hierarchical_position: 'Asistente',
      company_position: 'Asistente',
      normal_hours: '8',
      type_of_contract: 'A tiempo indeterminado',
      allocated_to: 'Empresa 5', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'Fernández',
      firstname: 'Laura',
      document_type: 'DNI',
      birthplace: 'Mar del Plata',
      gender: 'Femenino',
      marital_status: 'Soltera',
      level_of_education: 'Secundario',
      street: 'Calle 789',
      street_number: '123',
      province: 'Buenos Aires',
      postal_code: '5678',
      phone: '67890123',
      file: '123',
      date_of_admission: '01/05/2025',
      affiliate_status: 'Fuera de convenio',
      city: 'Mar del Plata',
      hierrical_position: 'Asistente',
      workflow_diagram: '123',
    },

    {
      full_name: 'Carlos Martínez',
      email: 'carlos.martinez@example.com',
      cuil: '26-78901234-5',
      document_number: '78901234',
      hierarchical_position: 'Operario',
      company_position: 'Operario',
      normal_hours: '8',
      type_of_contract: 'A tiempo determinado',
      allocated_to: 'Empresa 6', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'Martínez',
      firstname: 'Carlos',
      document_type: 'DNI',
      birthplace: 'La Plata',
      gender: 'Masculino',
      marital_status: 'Soltero',
      level_of_education: 'Primario',
      street: 'Avenida 012',
      street_number: '345',
      province: 'Buenos Aires',
      postal_code: '9012',
      phone: '78901234',
      file: '345',
      date_of_admission: '01/06/2026',
      affiliate_status: 'Convenio',
      city: 'La Plata',
      hierrical_position: 'Operario',
      workflow_diagram: '345',
    },

    {
      full_name: 'Sofía Morales',
      email: 'sofia.morales@example.com',
      cuil: '27-90123456-6',
      document_number: '90123456',
      hierarchical_position: 'Supervisor',
      company_position: 'Supervisor',
      normal_hours: '8',
      type_of_contract: 'A tiempo indeterminado',
      allocated_to: 'Empresa 7', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'Morales',
      firstname: 'Sofía',
      document_type: 'DNI',
      birthplace: 'Salta',
      gender: 'Femenino',
      marital_status: 'Soltera',
      level_of_education: 'Universitario',
      street: 'Calle 345',
      street_number: '678',
      province: 'Salta',
      postal_code: '1234',
      phone: '90123456',
      file: '678',
      date_of_admission: '01/07/2027',
      affiliate_status: 'Fuera de convenio',
      city: 'Salta',
      hierrical_position: 'Supervisor',
      workflow_diagram: '678',
    },
    {
      full_name: 'Luisa Herrera',
      email: 'luisa.herrera@example.com',
      cuil: '28-01234567-7',
      document_number: '01234567',
      hierarchical_position: 'Analista',
      company_position: 'Analista',
      normal_hours: '8',
      type_of_contract: 'A tiempo determinado',
      allocated_to: 'Empresa 8', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'Herrera',
      firstname: 'Luisa',
      document_type: 'DNI',
      birthplace: 'San Juan',
      gender: 'Femenino',
      marital_status: 'Soltera',
      level_of_education: 'Universitario',
      street: 'Avenida 678',
      street_number: '901',
      province: 'San Juan',
      postal_code: '5678',
      phone: '01234567',
      file: '901',
      date_of_admission: '01/08/2028',
      affiliate_status: 'Convenio',
      city: 'San Juan',
      hierrical_position: 'Analista',
      workflow_diagram: '901',
    },
    {
      full_name: 'Juan Pérez',
      email: 'juan.perez@example.com',
      cuil: '29-12345678-9',
      document_number: '12345678',
      hierarchical_position: 'Gerente',
      company_position: 'Gerente',
      normal_hours: '8',
      type_of_contract: 'A tiempo indeterminado',
      allocated_to: 'Empresa 9', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'Pérez',
      firstname: 'Juan',
      document_type: 'DNI',
      birthplace: 'Buenos Aires',
      gender: 'Masculino',
      marital_status: 'Casado',
      level_of_education: 'Universitario',
      street: 'Calle 123',
      street_number: '456',
      province: 'Buenos Aires',
      postal_code: '1234',
      phone: '12345678',
      file: '456',
      date_of_admission: '01/09/2029',
      affiliate_status: 'Fuera de convenio',
      city: 'Buenos Aires',
      hierrical_position: 'Gerente',
      workflow_diagram: '456',
    },
    {
      full_name: 'Ana López',
      email: 'ana.lopez@example.com',
      cuil: '30-23456789-0',
      document_number: '23456789',
      hierarchical_position: 'Supervisor',
      company_position: 'Supervisor',
      normal_hours: '8',
      type_of_contract: 'A tiempo determinado',
      allocated_to: 'Empresa 10', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'López',
      firstname: 'Ana',
      document_type: 'DNI',
      birthplace: 'Córdoba',
      gender: 'Femenino',
      marital_status: 'Soltera',
      level_of_education: 'Universitario',
      street: 'Avenida 789',
      street_number: '012',
      province: 'Córdoba',
      postal_code: '5678',
      phone: '23456789',
      file: '012',
      date_of_admission: '01/10/2030',
      affiliate_status: 'Convenio',
      city: 'Córdoba',
      hierrical_position: 'Supervisor',
      workflow_diagram: '012',
    },
    {
      full_name: 'Pedro Gómez',
      email: 'pedro.gomez@example.com',
      cuil: '31-34567890-1',
      document_number: '34567890',
      hierarchical_position: 'Operario',
      company_position: 'Operario',
      normal_hours: '8',
      type_of_contract: 'A tiempo indeterminado',
      allocated_to: 'Empresa 11', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'Gómez',
      firstname: 'Pedro',
      document_type: 'DNI',
      birthplace: 'Mendoza',
      gender: 'Masculino',
      marital_status: 'Casado',
      level_of_education: 'Secundario',
      street: 'Calle 456',
      street_number: '789',
      province: 'Mendoza',
      postal_code: '9012',
      phone: '34567890',
      file: '789',
      date_of_admission: '01/11/2031',
      affiliate_status: 'Fuera de convenio',
      city: 'Mendoza',
      hierrical_position: 'Operario',
      workflow_diagram: '789',
    },
    {
      full_name: 'María Rodríguez',
      email: 'maria.rodriguez@example.com',
      cuil: '32-45678901-2',
      document_number: '45678901',
      hierarchical_position: 'Analista',
      company_position: 'Analista',
      normal_hours: '8',
      type_of_contract: 'A tiempo determinado',
      allocated_to: 'Empresa 12', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'Rodríguez',
      firstname: 'María',
      document_type: 'DNI',
      birthplace: 'Tucumán',
      gender: 'Femenino',
      marital_status: 'Soltera',
      level_of_education: 'Universitario',
      street: 'Avenida 012',
      street_number: '345',
      province: 'Tucumán',
      postal_code: '3456',
      phone: '45678901',
      file: '345',
      date_of_admission: '01/12/2032',
      affiliate_status: 'Convenio',
      city: 'Tucumán',
      hierrical_position: 'Analista',
      workflow_diagram: '345',
    },
    {
      full_name: 'Laura Fernández',
      email: 'laura.fernandez@example.com',
      cuil: '33-56789012-3',
      document_number: '56789012',
      hierarchical_position: 'Supervisor',
      company_position: 'Supervisor',
      normal_hours: '8',
      type_of_contract: 'A tiempo indeterminado',
      allocated_to: 'Empresa 13', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'Fernández',
      firstname: 'Laura',
      document_type: 'DNI',
      birthplace: 'Santa Fe',
      gender: 'Femenino',
      marital_status: 'Casada',
      level_of_education: 'Universitario',
      street: 'Calle 789',
      street_number: '012',
      province: 'Santa Fe',
      postal_code: '6789',
      phone: '56789012',
      file: '012',
      date_of_admission: '01/01/2033',
      affiliate_status: 'Fuera de convenio',
      city: 'Santa Fe',
      hierrical_position: 'Supervisor',
      workflow_diagram: '012',
    },
    {
      full_name: 'Roberto Silva',
      email: 'roberto.silva@example.com',
      cuil: '34-67890123-4',
      document_number: '67890123',
      hierarchical_position: 'Operario',
      company_position: 'Operario',
      normal_hours: '8',
      type_of_contract: 'A tiempo determinado',
      allocated_to: 'Empresa 14', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'Silva',
      firstname: 'Roberto',
      document_type: 'DNI',
      birthplace: 'Chaco',
      gender: 'Masculino',
      marital_status: 'Soltero',
      level_of_education: 'Secundario',
      street: 'Avenida 345',
      street_number: '678',
      province: 'Chaco',
      postal_code: '8901',
      phone: '67890123',
      file: '678',
      date_of_admission: '01/02/2034',
      affiliate_status: 'Convenio',
      city: 'Chaco',
      hierrical_position: 'Operario',
      workflow_diagram: '678',
    },
    {
      full_name: 'Carolina Ramírez',
      email: 'carolina.ramirez@example.com',
      cuil: '35-78901234-5',
      document_number: '78901234',
      hierarchical_position: 'Analista',
      company_position: 'Analista',
      normal_hours: '8',
      type_of_contract: 'A tiempo indeterminado',
      allocated_to: 'Empresa 15', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'Ramírez',
      firstname: 'Carolina',
      document_type: 'DNI',
      birthplace: 'Entre Ríos',
      gender: 'Femenino',
      marital_status: 'Casada',
      level_of_education: 'Universitario',
      street: 'Calle 678',
      street_number: '901',
      province: 'Entre Ríos',
      postal_code: '2345',
      phone: '78901234',
      file: '901',
      date_of_admission: '01/03/2035',
      affiliate_status: 'Fuera de convenio',
      city: 'Entre Ríos',
      hierrical_position: 'Analista',
      workflow_diagram: '901',
    },
    {
      full_name: 'Fernando González',
      email: 'fernando.gonzalez@example.com',
      cuil: '36-90123456-6',
      document_number: '90123456',
      hierarchical_position: 'Supervisor',
      company_position: 'Supervisor',
      normal_hours: '8',
      type_of_contract: 'A tiempo determinado',
      allocated_to: 'Empresa 16', 
      picture: 'picture.com',
      nationality: 'Argentina',
      lastname: 'González',
      firstname: 'Fernando',
      document_type: 'DNI',
      birthplace: 'Corrientes',
      gender: 'Masculino',
      marital_status: 'Soltero',
      level_of_education: 'Secundario',
      street: 'Avenida 901',
      street_number: '234',
      province: 'Corrientes',
      postal_code: '5678',
      phone: '90123456',
      file: '234',
      date_of_admission: '01/04/2036',
      affiliate_status: 'Convenio',
      city: 'Corrientes',
      hierrical_position: 'Supervisor',
      workflow_diagram: '234',
    },
  ]

  return (
    <main className="flex flex-col ">
      <AlertComponent />
      <header className="flex flex-col gap-4 mt-6">
        <h2 className="text-4xl">Empleados</h2>
        <p>Aquí se muestra una tabla con los empleados registrados:</p>
      </header>

      <DataTable columns={columns} data={data} />
      <div className="mt-4">
        <Link
          href="/dashboard/employee/new"
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
        >
          Agregar nuevo empleado
        </Link>
      </div>
    </main>
  )
}

export default EmployeePage
