create table "public"."handle_errors" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "menssage" text not null,
    "path" text not null
);


alter table "public"."handle_errors" enable row level security;

alter table "public"."document_types" add column "private" boolean;

CREATE UNIQUE INDEX handle_errors_pkey ON public.handle_errors USING btree (id);

alter table "public"."handle_errors" add constraint "handle_errors_pkey" PRIMARY KEY using index "handle_errors_pkey";

grant delete on table "public"."handle_errors" to "anon";

grant insert on table "public"."handle_errors" to "anon";

grant references on table "public"."handle_errors" to "anon";

grant select on table "public"."handle_errors" to "anon";

grant trigger on table "public"."handle_errors" to "anon";

grant truncate on table "public"."handle_errors" to "anon";

grant update on table "public"."handle_errors" to "anon";

grant delete on table "public"."handle_errors" to "authenticated";

grant insert on table "public"."handle_errors" to "authenticated";

grant references on table "public"."handle_errors" to "authenticated";

grant select on table "public"."handle_errors" to "authenticated";

grant trigger on table "public"."handle_errors" to "authenticated";

grant truncate on table "public"."handle_errors" to "authenticated";

grant update on table "public"."handle_errors" to "authenticated";

grant delete on table "public"."handle_errors" to "service_role";

grant insert on table "public"."handle_errors" to "service_role";

grant references on table "public"."handle_errors" to "service_role";

grant select on table "public"."handle_errors" to "service_role";

grant trigger on table "public"."handle_errors" to "service_role";

grant truncate on table "public"."handle_errors" to "service_role";

grant update on table "public"."handle_errors" to "service_role";

create policy "Actualizar tipo de de documento"
on "public"."document_types"
as permissive
for update
to authenticated
using (true);


create policy "Permitir eliminar"
on "public"."documents_company"
as permissive
for delete
to authenticated
using (true);


create policy "Permitir eliminar "
on "public"."documents_employees"
as permissive
for delete
to authenticated
using (true);


create policy "Permitir Eliminar"
on "public"."documents_equipment"
as permissive
for delete
to authenticated
using (true);


create policy "Permitir todos los permisos"
on "public"."handle_errors"
as permissive
for all
to authenticated
using (true);



